---
# Source: template-arhat-device-go/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: template-arhat-device-go
  namespace: default
  labels:
    helm.sh/chart: template-arhat-device-go-0.1.0
    app.kubernetes.io/name: template-arhat-device-go
    app.kubernetes.io/instance: template-arhat-device-go
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
data:
  config.yaml: |
    templateArhatDevice:
      endpoint: unix:///var/run/arhat.sock
      log:
      - file: stderr
        format: console
        level: verbose
      tls:
        caCert: /path/to/caCert
        cert: /path/to/client-cert
        enabled: false
        insecureSkipVerify: true
        key: /path/to/client-cert-key
---
# Source: template-arhat-device-go/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: template-arhat-device-go
  namespace: default
  labels:
    helm.sh/chart: template-arhat-device-go-0.1.0
    app.kubernetes.io/name: template-arhat-device-go
    app.kubernetes.io/instance: template-arhat-device-go
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: template-arhat-device-go
      app.kubernetes.io/instance: template-arhat-device-go
  template:
    metadata:
      labels:
        app.kubernetes.io/name: template-arhat-device-go
        app.kubernetes.io/instance: template-arhat-device-go
    spec:
      securityContext:
        {}
      tolerations:
        - key: arhat.dev/namespace
          value: default
        - key: node.kubernetes.io/unschedulable
          operator: Exists
      containers:
        - name: arhat-device
          securityContext:
            {}
          image: "docker.io/arhatdev/template-arhat-device-go:1.16.0"
          imagePullPolicy: IfNotPresent
          command:
            - /template-arhat-device-go
            - -c
            - /etc/template-arhat-device-go/config.yaml
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: config
              mountPath: /etc/template-arhat-device-go
          resources:
            {}
      nodeSelector:
        arhat.dev/namespace: default
      volumes:
        - name: config
          configMap:
            name: template-arhat-device-go
